### ISSUE TITLE
Trapezoidal cartesian velocity profile with trajectory 

### ISSUE THREAD

**Issue by lakshmip001** [tobiaskunz/trajectories#5]
Can I get trajectory with trapezoidal Cartesian velocity profile and collision detection using this trajectories package?

**Comment by mirkow** [comment]
This package wont do any collision detection I guess

**Comment by lakshmip001** [comment]
ok. I see bounds on joint velocities and accelerations , using this trajectories packages can I obtain trapezoidal Cartesian Velocity profile for a 6DOF robotic arm?

**Comment by mirkow** [comment]
This package has nothing to do with joints or Cartesian velocities. It is just trajectories.
Cartesian Position will work, orientation wont work  since it would need special treatment of orientations.

**Comment by lakshmip001** [comment]
ok. I am looking for package, in which I can control Cartesian Velocity (trapezoidal velocity profile) for a 6DOF robotic arm UR5.

**Comment by BrettHemes-3M** [comment]
I'd be interested to hear what you find.  I ended up writing a package to
do this as I couldn't find any existing. Depending on your
needs/interest/timeframe I could probably share what I have.  It still
needs documentation and some better error handling but has some decent
functionality.

**Comment by lakshmip001** [comment]
Currently I ended up with trajopt +Moveit (openrave) , but the thing is Cartesian velocity has to be linked too many parameters where I don't get a relation on the obtained velocity . I mean trajectory is optimised using trajopt with only joint valves with a constraints on joint velocities and Cartesian velocities , while the velocities and accelerations are generated using Moveit or Openrave . So , I don't get a relation for the obtained velocity and constraints defined. I am still searching if I can find a better solution.   It will be great if I  can get the link of already written package or any suggestions on how I can proceed .

**Comment by BrettHemes-3M** [comment]
Let me see what I can do to get what I have released.  What is your time
frame like?  Is a couple of weeks too long?

**Comment by lakshmip001** [comment]
Currently I am still searching for a solution . So , time frame is not fixed but if I find a solution early it will be better . I can implement it and test it for fitting into my application.
